language: ruby
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2
  - 2.1
  - 2.0
sudo: false
gemfile: Gemfile
script: bundle exec rspec spec
addons:
  code_climate:
    repo_token: d20c1b4862616550a65962ceecf0299c70a844cbce54a230b5234804ac2725dc
after_success:
  - bundle exec codeclimate-test-reporter
